// =============================================================================
// Room Scope Prompt — analysis instructions for the Room / Project Scope Engine
// =============================================================================
// Builds the system prompt dynamically, using the v3 task library.
// The library block is generated by buildLibraryPromptBlock() to always stay
// in sync with the task library without manual copy-paste.
//
// Each prompt section teaches the model:
//   1. How to detect the stage of work
//   2. How to classify elements, materials, installations
//   3. How to split scope into required / likely / optional (matches library priority)
//   4. How to compute quantity hints from user-provided dimensions
//   5. What belongs in suggested_estimate_items (flat list for form pre-fill)
// =============================================================================

import { buildLibraryPromptBlock } from '../bathroom-task-library'

/** Build the full room scope system prompt with the current v3 library inlined. */
export function buildRoomScopeSystemPrompt(): string {
  const libraryBlock = buildLibraryPromptBlock()

  return `Jesteś ekspertem od remontów i wykończeń wnętrz w Polsce (specjalizacja: łazienki, kuchnie, pokoje).
Analizujesz zdjęcia pomieszczeń i na podstawie:
- widocznych elementów, materiałów, stanu technicznego, urządzeń
- przekazanych parametrów (powierzchnia, wysokość, instalacje, standard)
- aktualnej biblioteki pozycji branżowych (v3)
- zasad remontowych (priorytety, zależności między pozycjami)

generujesz KOMPLETNY, USTRUKTURYZOWANY zakres prac remontowych — jak kosztorysant branżowy.

Zwróć TYLKO poprawny JSON zgodny z podanym schematem.

${libraryBlock}

═══════════════════════════════════════════════════════════════
ZASADY WYKRYWANIA ETAPU PRAC (stage_of_work):
═══════════════════════════════════════════════════════════════
- before_renovation: stara łazienka/kuchnia w użytkowaniu, widoczne stare okładziny, zużyta armatura
- demolition: kucie, wyburzone ściany/podłogi, exposed beton/cegła, gruz
- shell: surowy stan bez okładzin, gołe ściany po tynku, brak armatury
- in_progress: mix — część prac wykonana (np. hydroizolacja), część nie
- finishing: montaż armatury, akcesoriów, malowanie szpachlowanego
- after_renovation: nowe okładziny, nowa armatura, czyste wykończenie
- unknown: nie da się określić z dostępnych zdjęć

═══════════════════════════════════════════════════════════════
ZASADY WYKRYWANIA ELEMENTÓW (observed_elements):
═══════════════════════════════════════════════════════════════
Klasyfikuj widoczne elementy według typu:
- fixture: elementy sanitarne (wanna, prysznic, umywalka, WC, bidet)
- surface: okładziny, podłogi, ściany, sufit
- installation: widoczne rury, przewody, odpływ, gniazdo
- damage: pęknięcia, pleśń, odspojenia, zawilgocenia, uszkodzenia
- appliance: sprzęty (bojler, wentylator, ogrzewanie podłogowe)
- furniture: meble łazienkowe, szafki, lustra
Każdy element: label (PL), type, confidence, location (opcjonalnie)

ZASADY WYKRYWANIA INSTALACJI (detected_installations):
- Oddzielna lista dla instalacji: rury wod-kan, przewody elektryczne, odpływ liniowy,
  wentylator, mata grzewcza, grzejnik drabinkowy, bateria podtynkowa
- Jeśli widoczne — dodaj do detected_installations (typ: installation)

═══════════════════════════════════════════════════════════════
ZASADY PODZIAŁU ZAKRESU PRAC:
═══════════════════════════════════════════════════════════════
Rozdziel zakres prac na TRZY listy (nie mieszaj!):

required_work_scope — pozycje [OBOWIĄZKOWA] z biblioteki:
  - Dodaj ZAWSZE jeśli pomieszczenie pasuje (np. każda łazienka musi mieć hydroizolację)
  - Nawet jeśli nie widać ich na zdjęciu — są wymagane zasadami remontowymi
  - Przykłady: pomiar/inwentaryzacja, gruntowanie, hydroizolacja, fugowanie

likely_work_scope — pozycje [PRAWDOPODOBNA] z biblioteki:
  - Dodaj gdy widoczne przesłanki lub logicznie wynika z zakresu
  - Przykłady: demontaż starych płytek (jeśli widać stare), grzejnik, oświetlenie

optional_work_scope — pozycje [WARUNKOWA] lub [OPCJONALNA]:
  - Dodaj TYLKO gdy widoczne na zdjęciu LUB potwierdzone w danych od użytkownika
  - Przykłady: wnęka GK, WC podtynkowe (tylko jeśli widać stelaż lub user potwierdził)

ZASADY ZALEŻNOŚCI — sprawdź i dodaj automatycznie:
- WC podtynkowe (fix_wc_concealed) → dodaj zabudowę stelaża (gk_wc_frame)
- Odpływ liniowy → dodaj plumb_shower_drain
- Wanna (fix_bathtub) → dodaj plumb_bathtub + fit_bathtub_tap
- Rewizja (gk_inspection) → dodaj gk_pipe_casing
- Hydroizolacja strefy mokrej (waterproof_wet) → dodaj waterproof_tape, waterproof_collar
- Fugowanie ścian (tile_wall_grouting) → dodaj tile_wall_full lub tile_wall_partial

═══════════════════════════════════════════════════════════════
ZASADY ILOŚCI (quantity_hints + suggested_estimate_items):
═══════════════════════════════════════════════════════════════
Gdy użytkownik podał wymiary — oblicz i zapisz w quantity_hints:
- floor_area: area_m2 (podłoga)
- ceiling_area: = floor_area
- perimeter: 4 × √floor_area (przybliżenie dla prostokątnej łazienki)
- wall_area: perimeter × ceiling_height_m
- wet_zone_area: 1.2 jeśli prysznic, +1.6 jeśli wanna

Przy obliczaniu ilości w suggested_estimate_items:
- Podłoga: floor_area (tile_floor, waterproof_floor, paint_ceiling)
- Płytki ścienne pełna wys: wall_area. Częściowa: wall_area × 0.6. Brak: 0
- Malowanie ścian: wall_area minus powierzchnia pokryta płytkami
- Hydroizolacja strefy mokrej: wet_zone_area (minimum 1.2 m²)
- Confidence dla ilości: 85+ gdy masz dokładne wymiary, 45-65 gdy szacujesz, <30 gdy brak danych

═══════════════════════════════════════════════════════════════
ZASADY suggested_estimate_items (lista do wyceny):
═══════════════════════════════════════════════════════════════
- Generuj JEDNĄ płaską listę pozycji z WSZYSTKICH trzech list zakresu prac
- Kolejność: demontaż → przygotowanie → hydroizolacja → zabudowy → instalacje → okładziny → malowanie → biały montaż → armatura → akcesoria → uszczelnienia
- library_id: przepisz id z biblioteki (np. "waterproof_wet")
- name: użyj polskiej nazwy z biblioteki
- unit_price: ZAWSZE null (nie wymyślaj cen)
- source: zawsze "ai_suggestion"
- quantity: 0 z niskim confidence gdy brak danych

═══════════════════════════════════════════════════════════════
MISSING_INFORMATION + ASSUMPTIONS:
═══════════════════════════════════════════════════════════════
missing_information — pytania na które nie ma odpowiedzi:
  Przykłady: "Nieznana powierzchnia podłogi", "Brak informacji o typie WC",
  "Niewidoczny stan instalacji elektrycznej"

assumptions — co model założył:
  Przykłady: "Zakładam WC stojące — brak widocznego stelaża",
  "Zakładam standardową wysokość sufitu 2.6m",
  "Zakładam remont generalny"

═══════════════════════════════════════════════════════════════
ZASADY OGÓLNE:
═══════════════════════════════════════════════════════════════
- space_type: łazienka, kuchnia, pokój, korytarz, salon, sypialnia, wc, piwnica, inne
- confidence: 0-100 ogólna pewność analizy
- Preferuj null nad zgadywanie
- warnings: dodaj gdy obraz niewyraźny, ciemny, nie przedstawia pomieszczenia, poza zakresem
- Gdy wiele zdjęć — łącz informacje z WSZYSTKICH zdjęć
- To jest DRAFT wyceny — bądź kompletny ale zaznacz co jest założeniem`
}

/** Nullable string helper */
const ns = { anyOf: [{ type: 'string' }, { type: 'null' }] }
/** Nullable number helper */
const nn = { anyOf: [{ type: 'number' }, { type: 'null' }] }

const DETECTED_ELEMENT_SCHEMA = {
  type: 'object',
  properties: {
    type:       { type: 'string', enum: ['fixture', 'surface', 'installation', 'damage', 'appliance', 'furniture', 'other'] },
    label:      { type: 'string' },
    confidence: { type: 'number' },
    location:   ns,
    notes:      ns,
  },
  required: ['type', 'label', 'confidence', 'location', 'notes'],
  additionalProperties: false,
}

const DETECTED_MATERIAL_SCHEMA = {
  type: 'object',
  properties: {
    name:       { type: 'string' },
    category:   { type: 'string' },
    quantity:   nn,
    unit:       ns,
    confidence: { type: 'number' },
    notes:      ns,
  },
  required: ['name', 'category', 'quantity', 'unit', 'confidence', 'notes'],
  additionalProperties: false,
}

const SCOPE_ITEM_SCHEMA = {
  type: 'object',
  properties: {
    library_id:   ns,
    description:  { type: 'string' },
    category:     { type: 'string' },
    unit:         ns,
    quantity:     nn,
    priority:     { type: 'string', enum: ['required', 'likely', 'optional'] },
    confidence:   { type: 'number' },
    notes:        ns,
    dependencies: { type: 'array', items: { type: 'string' } },
  },
  required: ['library_id', 'description', 'category', 'unit', 'quantity', 'priority', 'confidence', 'notes', 'dependencies'],
  additionalProperties: false,
}

const QUANTITY_HINT_SCHEMA = {
  type: 'object',
  properties: {
    dimension:  { type: 'string', enum: ['floor_area', 'wall_area', 'ceiling_area', 'perimeter', 'wet_zone_area', 'other'] },
    value:      nn,
    unit:       { type: 'string' },
    source:     { type: 'string', enum: ['measured', 'estimated', 'user_input', 'ai_inferred', 'unknown'] },
    confidence: { type: 'number' },
  },
  required: ['dimension', 'value', 'unit', 'source', 'confidence'],
  additionalProperties: false,
}

const ESTIMATE_ITEM_SCHEMA = {
  type: 'object',
  properties: {
    library_id: ns,
    name:       { type: 'string' },
    unit:       { type: 'string' },
    quantity:   { type: 'number' },
    unit_price: nn,
    confidence: { type: 'number' },
    source:     { type: 'string', enum: ['ai_suggestion', 'market_data', 'historical'] },
    notes:      ns,
  },
  required: ['library_id', 'name', 'unit', 'quantity', 'unit_price', 'confidence', 'source', 'notes'],
  additionalProperties: false,
}

/** JSON schema for RoomAnalysisResult structured output (v2) */
export const ROOM_SCOPE_RESPONSE_SCHEMA = {
  type:   'json_schema',
  name:   'room_analysis_v2',
  strict: true,
  schema: {
    type: 'object',
    properties: {
      space_type:              ns,
      stage_of_work:           { type: 'string', enum: ['before_renovation', 'demolition', 'shell', 'in_progress', 'finishing', 'after_renovation', 'unknown'] },
      observed_elements:       { type: 'array', items: DETECTED_ELEMENT_SCHEMA },
      detected_installations:  { type: 'array', items: DETECTED_ELEMENT_SCHEMA },
      detected_materials:      { type: 'array', items: DETECTED_MATERIAL_SCHEMA },
      required_work_scope:     { type: 'array', items: SCOPE_ITEM_SCHEMA },
      likely_work_scope:       { type: 'array', items: SCOPE_ITEM_SCHEMA },
      optional_work_scope:     { type: 'array', items: SCOPE_ITEM_SCHEMA },
      missing_information:     { type: 'array', items: { type: 'string' } },
      assumptions:             { type: 'array', items: { type: 'string' } },
      quantity_hints:          { type: 'array', items: QUANTITY_HINT_SCHEMA },
      suggested_estimate_items: { type: 'array', items: ESTIMATE_ITEM_SCHEMA },
      coverage: {
        anyOf: [
          {
            type: 'object',
            properties: {
              total:     { type: 'number' },
              matched:   { type: 'number' },
              unmatched: { type: 'number' },
            },
            required: ['total', 'matched', 'unmatched'],
            additionalProperties: false,
          },
          { type: 'null' },
        ],
      },
      warnings:   { type: 'array', items: { type: 'string' } },
      confidence: { type: 'number' },
      notes:      ns,
    },
    required: [
      'space_type', 'stage_of_work', 'observed_elements', 'detected_installations',
      'detected_materials', 'required_work_scope', 'likely_work_scope', 'optional_work_scope',
      'missing_information', 'assumptions', 'quantity_hints', 'suggested_estimate_items',
      'coverage', 'warnings', 'confidence', 'notes',
    ],
    additionalProperties: false,
  },
}
