import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useCompanyId } from '@/features/auth/hooks/useAuth'
import { estimatesApi } from '@/features/estimates/api/estimates.api'
import { autoLinkService } from '@/services/project/autoLinkService'
import { useToast } from '@/shared/hooks/useToast'
import { translateError } from '@/shared/lib/errorMessages'
import type { Estimate } from '@/entities/estimate/model'

export const estimateKeys = { all: ['estimates'] as const, list: (companyId: string) => [...estimateKeys.all, 'list', companyId] as const }

export function useEstimates() { const companyId = useCompanyId(); return useQuery({ queryKey: estimateKeys.list(companyId), queryFn: () => estimatesApi.list(companyId) }) }
export function useCreateEstimate() { const companyId = useCompanyId(); const queryClient = useQueryClient(); const toast = useToast(); return useMutation({ mutationFn: estimatesApi.create, onSuccess: (data) => { queryClient.setQueryData<Estimate[]>(estimateKeys.list(companyId), (old = []) => [data, ...old]); queryClient.invalidateQueries({ queryKey: estimateKeys.list(companyId) }); queryClient.invalidateQueries({ queryKey: ['onboarding-progress', companyId] }); toast.success('Kosztorys utworzony'); autoLinkService.link({ type: 'estimate', id: data.id, companyId, clientId: data.client_id, projectId: data.project_id ?? null }).then(() => { if (data.project_id) queryClient.invalidateQueries({ queryKey: ['projects', companyId] }) }).catch((err) => console.warn('[autoLink] estimate link failed:', err)) }, onError: (error: any) => { const msg = error?.message ?? error?.details ?? 'Sprawdź połączenie i spróbuj ponownie'; toast.error('Nie udało się utworzyć kosztorysu', msg); console.error('[estimates] create error:', error) } }) }
export function useUpdateEstimate() { const companyId = useCompanyId(); const queryClient = useQueryClient(); const toast = useToast(); return useMutation({ mutationFn: ({ id, input }: { id: string; input: Partial<Estimate> }) => estimatesApi.update(id, input, companyId), onSuccess: (data) => { const updated = data as Estimate; queryClient.setQueryData<Estimate[]>(estimateKeys.list(companyId), (old = []) => old.map(e => e.id === updated.id ? updated : e)); queryClient.invalidateQueries({ queryKey: estimateKeys.list(companyId) }); toast.success('Kosztorys zaktualizowany') }, onError: (error: any) => { const msg = error?.message ?? error?.details ?? 'Sprawdź połączenie i spróbuj ponownie'; toast.error('Błąd zapisu wyceny', msg); console.error('[estimates] update error:', error) } }) }
export function useDeleteEstimate() { const companyId = useCompanyId(); const queryClient = useQueryClient(); const toast = useToast(); return useMutation({ mutationFn: (id: string) => estimatesApi.delete(id, companyId), onSuccess: (_, id) => { queryClient.setQueryData<Estimate[]>(estimateKeys.list(companyId), (old = []) => old.filter(e => e.id !== id)); queryClient.invalidateQueries({ queryKey: estimateKeys.list(companyId) }); queryClient.invalidateQueries({ queryKey: ['project_documents'] }); toast.info('Kosztorys usunięty') }, onError: (error) => toast.error('Nie udało się usunąć kosztorysu', translateError(error)) }) }
