// =============================================================================
// Clarification / Question Engine — canonical types (v1)
// =============================================================================
// Defines the typed model for AI-generated clarification questions.
//
// These types mirror the shape exported from:
//   netlify/functions/shared/bathroom-triggers.ts
// Both definitions must remain structurally compatible (JSON serialisation bridges them).
//
// Question lifecycle:
//   1. expandDependencies() in bathroom-triggers.ts → ClarificationQuestion[]
//   2. Netlify function injects them into result.clarification_questions
//   3. Client receives them via RoomAnalysisResult / ProjectAnalysisResult
//   4. ClarificationQuestionsSection renders them grouped by severity
// =============================================================================

/** How important the answer is for producing a correct scope/estimate */
export type QuestionSeverity =
  | 'critical_for_scope'       // answer adds or removes tasks — scope changes materially
  | 'important_for_accuracy'   // answer affects quantities or which variant is used
  | 'optional_detail'          // affects spec/material choice only — scope stays the same

/** Expected answer format — used to inform future interactive form */
export type QuestionAnswerType =
  | 'yes_no'          // Tak / Nie
  | 'single_choice'   // pick one from options (defined in relatedTaskIds context)
  | 'number'          // numeric value (dimension, count)
  | 'text'            // free text

/** Thematic grouping of the question */
export type QuestionCategory =
  | 'scope'           // zakres prac — co wchodzi / co nie
  | 'installation'    // sposób montażu / typ instalacji
  | 'location'        // lokalizacja elementu (zmiana / brak zmiany)
  | 'material'        // specyfikacja materiału
  | 'electrical'      // związane z instalacją elektryczną
  | 'other'

/**
 * A single structured clarification question generated by the dependency engine.
 * Supplements the plain text questions already present in missing_information[].
 */
export interface ClarificationQuestion {
  /** Stable identifier — e.g. 'linear_drain_q1'. Used for deduplication. */
  id: string

  /** Polish question text shown to the user */
  text: string

  /** Determines visual priority in the grouped UI */
  severity: QuestionSeverity

  /** Thematic grouping */
  category: QuestionCategory

  /** Expected answer format */
  answerType: QuestionAnswerType

  /** triggerId that generated this question (e.g. 'linear_drain') */
  relatedTrigger: string

  /**
   * Library IDs of tasks whose inclusion depends on the answer.
   * Empty = the answer refines how an existing task is executed.
   */
  relatedTaskIds: string[]

  /**
   * Plain-text descriptions of what changes based on the answer.
   * Used for tooltip / hover context.
   */
  affects: string[]

  /** Origin of the question */
  source: 'dependency_rule' | 'ai' | 'user_required'

  /** For single_choice: selectable Polish labels shown as buttons */
  options?: string[]
}

// ── Answer model (v1) ─────────────────────────────────────────────────────────────

/** Polymorphic answer value */
export type AnswerValue = string | boolean | number

/**
 * A user-provided answer to one clarification question.
 * Stored in session state; drives applyAnswersToResult().
 */
export interface ClarificationAnswer {
  /** Matches ClarificationQuestion.id */
  questionId: string

  /** The value the user selected or typed */
  answerValue: AnswerValue

  /** ISO timestamp when the answer was recorded */
  answeredAt: string

  /** Always 'user' for v1 */
  source: 'user'

  /** Copied from ClarificationQuestion.affects for auditing */
  affects: string[]

  /** Optional: confidence delta applied to relatedTaskIds (derived by effects engine) */
  confidenceImpact?: number
}
