-- 082_invoice_draft_status.sql
-- Introduces draft support for invoices so that a sequential FV/... number
-- is consumed ONLY at issuance, not at draft creation.
--
-- Changes:
--   1. invoices.status CHECK extended with 'draft'
--   2. invoices.number made nullable — NULL is only allowed for drafts
--      (a separate CHECK enforces: non-draft MUST have a number)
--
-- Existing invoices are unaffected. No data migration needed.
-- The constraint name used in the original schema was generated by PG from the
-- column definition; safest approach is DROP CONSTRAINT … IF EXISTS for all
-- known variants, then re-add explicitly named constraints.

-- ── Step 1: extend status ─────────────────────────────────────────────────────

-- Drop all plausible autogenerated check-constraint names (PG names table-level
-- checks as <table>_<col>_check, or with _1, _2 suffix if duplicated).
ALTER TABLE public.invoices DROP CONSTRAINT IF EXISTS invoices_status_check;
ALTER TABLE public.invoices DROP CONSTRAINT IF EXISTS invoices_status_check1;
ALTER TABLE public.invoices DROP CONSTRAINT IF EXISTS invoices_status_check2;

ALTER TABLE public.invoices
  ADD CONSTRAINT invoices_status_check
  CHECK (status IN ('unpaid', 'paid', 'overdue', 'draft'));

-- ── Step 2: allow NULL number for draft rows ──────────────────────────────────

-- Drop the NOT NULL constraint
ALTER TABLE public.invoices
  ALTER COLUMN number DROP NOT NULL;

-- Enforce: only draft rows may have number = NULL
ALTER TABLE public.invoices DROP CONSTRAINT IF EXISTS invoices_number_required_when_issued;

ALTER TABLE public.invoices
  ADD CONSTRAINT invoices_number_required_when_issued
  CHECK (status = 'draft' OR number IS NOT NULL);
