import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useCompanyId } from '@/features/auth/hooks/useAuth'
import { invoicesApi } from '@/features/invoices/api/invoices.api'
import { autoLinkService } from '@/services/project/autoLinkService'
import { useToast } from '@/shared/hooks/useToast'
import { translateError } from '@/shared/lib/errorMessages'
import type { Invoice } from '@/entities/invoice/model'

const invoiceKeys = { all: ['invoices'] as const, list: (companyId: string) => [...invoiceKeys.all, companyId] as const }
export function useInvoices() { const companyId = useCompanyId(); return useQuery({ queryKey: invoiceKeys.list(companyId), queryFn: () => invoicesApi.list(companyId) }) }
export function useCreateInvoice() { const companyId = useCompanyId(); const qc = useQueryClient(); const toast = useToast(); return useMutation({ mutationFn: invoicesApi.create, onSuccess: (data) => { qc.invalidateQueries({ queryKey: invoiceKeys.list(companyId) }); qc.invalidateQueries({ queryKey: ['dashboard', companyId] }); toast.success('Faktura utworzona'); if (data.project_id) qc.invalidateQueries({ queryKey: ['project_documents', data.project_id] }); autoLinkService.link({ type: 'invoice', id: data.id, companyId, clientId: data.client_id, projectId: data.project_id ?? null, sourceType: 'contract', sourceId: data.contract_id ?? null }).catch(() => {}) }, onError: (error) => toast.error('Nie udało się utworzyć faktury', translateError(error)) }) }
export function useUpdateInvoice() { const companyId = useCompanyId(); const qc = useQueryClient(); const toast = useToast(); return useMutation({ mutationFn: ({ id, input }: { id: string; input: Partial<Invoice> }) => invoicesApi.update(id, input, companyId), onSuccess: () => { qc.invalidateQueries({ queryKey: invoiceKeys.list(companyId) }); toast.success('Faktura zaktualizowana') } }) }
export function useDeleteInvoice() { const companyId = useCompanyId(); const qc = useQueryClient(); const toast = useToast(); return useMutation({ mutationFn: (id: string) => invoicesApi.delete(id, companyId), onSuccess: () => { qc.invalidateQueries({ queryKey: invoiceKeys.list(companyId) }); qc.invalidateQueries({ queryKey: ['dashboard', companyId] }); qc.invalidateQueries({ queryKey: ['project_documents'] }); toast.info('Faktura usunięta') } }) }
export function useMarkInvoicePaid() { const companyId = useCompanyId(); const qc = useQueryClient(); const toast = useToast(); return useMutation({ mutationFn: (id: string) => invoicesApi.markPaid(id, companyId), onSuccess: () => { qc.invalidateQueries({ queryKey: invoiceKeys.list(companyId) }); qc.invalidateQueries({ queryKey: ['dashboard', companyId] }); toast.success('Faktura oznaczona jako opłacona') } }) }
export function useSendInvoiceToKsef() { const companyId = useCompanyId(); const qc = useQueryClient(); const toast = useToast(); return useMutation({ mutationFn: (id: string) => invoicesApi.sendToKsef(id, companyId), onSuccess: () => { qc.invalidateQueries({ queryKey: invoiceKeys.list(companyId) }); toast.success('Faktura dodana do kolejki KSeF') }, onError: (error) => toast.error('Nie udało się dodać do kolejki KSeF', translateError(error)) }) }
export function useCreateInvoiceFromEstimate() { const companyId = useCompanyId(); const qc = useQueryClient(); const toast = useToast(); return useMutation({ mutationFn: (estimateId: string) => invoicesApi.createFromEstimate(companyId, estimateId), onSuccess: (data, estimateId) => { qc.invalidateQueries({ queryKey: invoiceKeys.list(companyId) }); qc.invalidateQueries({ queryKey: ['dashboard', companyId] }); toast.success('Faktura wygenerowana z kosztorysu'); if (data.project_id) qc.invalidateQueries({ queryKey: ['project_documents', data.project_id] }); autoLinkService.link({ type: 'invoice', id: data.id, companyId, clientId: data.client_id, projectId: data.project_id ?? null, sourceType: 'estimate', sourceId: estimateId }).catch(() => {}) }, onError: (error) => toast.error('Nie udało się wygenerować faktury', translateError(error)) }) }
export function useCreateInvoiceFromContract() { const companyId = useCompanyId(); const qc = useQueryClient(); const toast = useToast(); return useMutation({ mutationFn: (contractId: string) => invoicesApi.createFromContract(companyId, contractId), onSuccess: (data) => { qc.invalidateQueries({ queryKey: invoiceKeys.list(companyId) }); qc.invalidateQueries({ queryKey: ['dashboard', companyId] }); toast.success('Faktura wygenerowana z umowy'); if (data.project_id) qc.invalidateQueries({ queryKey: ['project_documents', data.project_id] }); autoLinkService.link({ type: 'invoice', id: data.id, companyId, clientId: data.client_id, projectId: data.project_id ?? null, sourceType: 'contract', sourceId: data.contract_id ?? null }).catch(() => {}) }, onError: (error) => toast.error('Nie udało się wygenerować faktury', translateError(error)) }) }
